services:
  clft-zod:
    build:
      context: .
      dockerfile: Dockerfile
    image: clft-zod:latest
    container_name: clft-zod
    volumes:
      - ./:/workspace
    environment:
      - PYTHONPATH=/workspace
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    working_dir: /workspace
